<?php

/*
 * TheRain Unified module manifest.
 *
 * Only modules marked enabled are loadable. Planned management systems are
 * registered with status "planned" so their metadata (database location,
 * future dependencies) has one place to live, but they carry no routes,
 * permissions, or database content until they are actually implemented —
 * see docs/MODULE-DATABASE-ARCHITECTURE.md.
 *
 * Field meaning:
 *   database    - path to the module's standalone schema, relative to the
 *                  repository root. Present even for planned modules so the
 *                  location is reserved; the file itself may not exist yet
 *                  (see standalone_ready).
 *   migrations  - path to module-specific migrations, once any exist.
 *   standalone_ready - true only when `database` points at a real,
 *                  reviewed db.sql that can run without any other module.
 *   unified_ready - true only when the module's schema has been folded
 *                  into database/dbumi.sql.
 *   licensing   - placeholder for future per-module licensing metadata.
 *                  Not enforced by any code in Phase 4.
 */
return array(
    'pharmacy' => array(
        'name' => 'Pharmacy Management',
        'slug' => 'pharmacy',
        'version' => '1.0.0-legacy',
        'type' => 'management-system',
        'enabled' => true,
        'status' => 'legacy-compatible',
        'path' => 'management/pharmacy',
        'database' => 'management/pharmacy/database/db.sql',
        'migrations' => null,
        'dependencies' => array(),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => true,
        'unified_ready' => true,
        'licensing' => array('required' => false, 'notes' => 'Not yet enforced.'),
        'notes' => 'The existing Pharmacy POS remains at legacy root routes during the staged migration. Its schema requires zero core tables today; see docs/PHARMACY-DATABASE-MIGRATION-PLAN.md.',
    ),
    'supermarket' => array(
        'name' => 'Supermarket Management',
        'slug' => 'supermarket',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/supermarket',
        'database' => 'management/supermarket/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'pos' => array(
        'name' => 'POS Management',
        'slug' => 'pos',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/pos',
        'database' => 'management/pos/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'hospital' => array(
        'name' => 'Hospital Management',
        'slug' => 'hospital',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/hospital',
        'database' => 'management/hospital/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'shop' => array(
        'name' => 'Shop Management',
        'slug' => 'shop',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/shop',
        'database' => 'management/shop/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'mobile-shop' => array(
        'name' => 'Mobile Shop Management',
        'slug' => 'mobile-shop',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/mobile-shop',
        'database' => 'management/mobile-shop/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented. Schema plan documented at docs/MOBILE-SHOP-DATABASE-PLAN.md.',
    ),
    'hotel' => array(
        'name' => 'Hotel Management',
        'slug' => 'hotel',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/hotel',
        'database' => 'management/hotel/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'restaurant' => array(
        'name' => 'Restaurant Management',
        'slug' => 'restaurant',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/restaurant',
        'database' => 'management/restaurant/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'school' => array(
        'name' => 'School Management',
        'slug' => 'school',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/school',
        'database' => 'management/school/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
    'warehouse' => array(
        'name' => 'Warehouse Management',
        'slug' => 'warehouse',
        'version' => null,
        'type' => 'management-system',
        'enabled' => false,
        'status' => 'planned',
        'path' => 'management/warehouse',
        'database' => 'management/warehouse/database/db.sql',
        'migrations' => null,
        'dependencies' => array('core'),
        'permissions' => array(),
        'routes' => array(),
        'standalone_ready' => false,
        'unified_ready' => false,
        'licensing' => array('required' => false, 'notes' => null),
        'notes' => 'Not implemented.',
    ),
);
