<?php

/**
 * Task 4 (Phase 7): build dbumi.sql for real, import it into its own
 * disposable database, and diff its CORE tables against the
 * migration-built test database. This is the automated form of the
 * manual check performed in Phase 6 — see docs/DBUMI-VALIDATION-REPORT.md.
 */
function therain_test_run_dbumi_consistency()
{
    therain_test_section('Database: dbumi.sql consistency with migrations');

    require_once THERAIN_APP_ROOT . '/database/build-dbumi.php';

    $dbConfig = therain_config('database');
    $dbumiDatabaseName = $GLOBALS['therain_test_database_name'] . '_dbumi';
    $dbumiPath = THERAIN_APP_ROOT . '/database/dbumi.sql';

    // 1. Build dbumi.sql for real via the actual builder function — not
    // by spawning it as a subprocess. Phase 7 found that exec()'ing a
    // nested `php` process from a process that already holds a mysqli
    // connection (which this test process does) reliably crashes PHP
    // 8.0.28 on Windows with no catchable error at all. Calling the
    // function directly exercises the exact same build logic without
    // that risk — see docs/TEST-SUITE-REPORT.md.
    try {
        $output = therain_build_dbumi_sql(THERAIN_APP_ROOT);
        therain_test_assert('database/build-dbumi.php builds without error', true);
    } catch (RuntimeException $exception) {
        therain_test_assert('database/build-dbumi.php builds without error', false, $exception->getMessage());
        return;
    }

    file_put_contents($dbumiPath, $output);
    therain_test_assert('database/dbumi.sql was written', is_file($dbumiPath));

    // 2. Building again should now match what's already on disk (drift check).
    $secondBuild = therain_build_dbumi_sql(THERAIN_APP_ROOT);
    $normalize = function ($text) {
        return preg_replace('/^-- GENERATED by database\/build-dbumi\.php on .*$/m', '-- GENERATED by database/build-dbumi.php on <timestamp>', $text);
    };
    therain_test_assert('re-building immediately after produces identical output (deterministic)', $normalize($output) === $normalize($secondBuild));

    // 3. Import the freshly built file into its own disposable database.
    // Uses therain_test_multi_query() (tests/bootstrap.php) rather than
    // mysqli::multi_query() directly, and rather than shelling out to an
    // external `mysql` client binary — see that function's docstring for
    // the crash this avoids, and docs/TEST-SUITE-REPORT.md.
    $adminConnection = new mysqli($dbConfig['host'], $dbConfig['username'], $dbConfig['password'], '', (int) $dbConfig['port']);
    $adminConnection->query('DROP DATABASE IF EXISTS `' . $adminConnection->real_escape_string($dbumiDatabaseName) . '`');
    $adminConnection->query('CREATE DATABASE `' . $adminConnection->real_escape_string($dbumiDatabaseName) . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
    $adminConnection->close();

    $dbumiConnection = new mysqli($dbConfig['host'], $dbConfig['username'], $dbConfig['password'], $dbumiDatabaseName, (int) $dbConfig['port']);
    $dbumiConnection->set_charset($dbConfig['charset']);

    $dbumiSqlContent = file_get_contents($dbumiPath);
    $importError = therain_test_multi_query($dbumiConnection, $dbumiSqlContent);

    therain_test_assert('dbumi.sql imports without error', $importError === null, (string) $importError);

    // 4. Diff every CORE table (everything except schema_migrations and
    // Pharmacy's own tables) between the migration-built database and the
    // dbumi-built one.
    $coreTables = array(
        'tenants', 'tenant_settings', 'tenant_modules', 'users', 'user_profiles',
        'user_sessions', 'roles', 'permissions', 'role_permissions', 'user_roles',
        'branches', 'warehouses', 'login_attempts', 'activity_logs', 'audit_logs',
        'notifications', 'notification_preferences', 'system_settings',
        'payment_methods', 'currencies', 'languages', 'tenant_currency_settings',
        'user_currency_preferences', 'exchange_rates', 'tenant_payment_methods',
        'branch_payment_methods', 'payment_method_currencies', 'cashier_shifts',
        'payments', 'payment_refunds', 'financial_settings',
    );

    $migrationDb = therain_test_db();
    $mismatches = array();

    foreach ($coreTables as $table) {
        $migrationCreate = $migrationDb->query("SHOW CREATE TABLE `$table`")->fetch_assoc()['Create Table'];
        $dbumiCreate = $dbumiConnection->query("SHOW CREATE TABLE `$table`")->fetch_assoc()['Create Table'];

        $normalize = function ($sql) {
            return preg_replace('/AUTO_INCREMENT=\d+\s*/', '', $sql);
        };

        if ($normalize($migrationCreate) !== $normalize($dbumiCreate)) {
            $mismatches[] = $table;
        }
    }

    therain_test_assert('all ' . count($coreTables) . ' CORE tables are structurally identical between migration and dbumi paths', empty($mismatches), implode(', ', $mismatches));

    // 5. Confirm Pharmacy's schema landed in the dbumi-built database too.
    $pharmacyTableCheck = $dbumiConnection->query("SHOW TABLES LIKE 'p_medicine'")->num_rows;
    therain_test_assert('Pharmacy tables (e.g. p_medicine) are present in the dbumi-built database', $pharmacyTableCheck === 1);

    $totalTables = $dbumiConnection->query(
        "SELECT COUNT(*) AS c FROM information_schema.tables WHERE table_schema = '" . $dbumiConnection->real_escape_string($dbumiDatabaseName) . "'"
    )->fetch_assoc()['c'];
    therain_test_assert('dbumi-built database has 55 tables total (32 CORE + 23 Pharmacy)', (int) $totalTables === 55, "actual=$totalTables");

    // 6. No duplicate table names anywhere in the generated file (the
    // builder already enforces this at build time; re-check the output
    // directly here as a second, independent verification).
    $dbumiSql = file_get_contents($dbumiPath);
    preg_match_all('/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?([a-zA-Z0-9_]+)`?/i', $dbumiSql, $matches);
    $names = $matches[1];
    therain_test_assert('no duplicate CREATE TABLE names in the generated dbumi.sql', count($names) === count(array_unique($names)));

    // 7. Non-ASCII seed data survived the import correctly (the Phase 6 charset bug).
    $arabicName = $dbumiConnection->query("SELECT native_name FROM languages WHERE code = 'ar'")->fetch_assoc()['native_name'];
    therain_test_assert('Arabic language name imports correctly (no mojibake)', $arabicName === 'العربية', $arabicName);

    $dbumiConnection->close();
}
