-- ============================================================================
-- THERAIN UNIFIED — COMPLETE (dbumi) DATABASE
-- ============================================================================
-- dbumi.sql = CORE (shared platform schema) + the schema of every ENABLED
-- management module, combined. As of Phase 5, Pharmacy is still the only
-- enabled module (modules/manifest.php), so this file currently contains:
--
--   1. CORE   — the shared identity/platform schema, equivalent to applying
--                database/migrations/0001_initial_unified_schema.sql,
--                0002_identity_foundation.sql, and
--                0003_financial_foundation.sql to an empty database (every
--                ALTER TABLE column from 0002/0003 is written directly into
--                its CREATE TABLE statement here, since this file
--                represents a fresh-install target state, not a migration
--                history). 0003 adds the currency/payment-method/financial
--                foundation: currencies and payment_methods gained new
--                columns, and nine new tables were added
--                (tenant_currency_settings, user_currency_preferences,
--                exchange_rates, tenant_payment_methods,
--                branch_payment_methods, payment_method_currencies,
--                cashier_shifts, payments, payment_refunds) plus
--                financial_settings.
--   2. PHARMACY MODULE — the unmodified legacy Pharmacy schema, identical to
--                management/pharmacy/database/db.sql (minus its own
--                CREATE DATABASE/USE/DROP statements, which do not apply
--                inside a shared database). Pharmacy's own separate
--                `payment_method` (singular) table is untouched by, and
--                unrelated to, CORE's `payment_methods` (plural) catalog.
--
-- IMPORTANT — KNOWN, DOCUMENTED INCONSISTENCY:
-- CORE and PHARMACY MODULE are two coexisting, NOT YET CROSS-REFERENCED
-- identity systems. CORE uses tenants/users/branches; Pharmacy still uses
-- its own `store` table and store_id. No foreign key connects them. This
-- is intentional and matches every prior phase's compatibility decision
-- (see docs/AUTHENTICATION-ARCHITECTURE.md, docs/TENANT-ARCHITECTURE.md).
-- Reconciling them is a separate, later, audited migration — see
-- docs/PHARMACY-DATABASE-MIGRATION-PLAN.md. Do not treat this file as
-- evidence that Pharmacy has been integrated into the tenant model.
--
-- MAINTENANCE (manual, reviewed process — see docs/DBUMI-ARCHITECTURE.md):
-- This file is hand-composed and hand-reviewed, not generated by an
-- automatic build script. When a new module is enabled in
-- modules/manifest.php, its management/<slug>/database/db.sql content is
-- reviewed for table-name collisions against every existing section, then
-- appended here as a new section, and this header is updated. There is no
-- tool that runs this automatically; that is a deliberate choice to avoid
-- silently concatenating unreviewed SQL into a database file relied upon by
-- real installations.
--
-- USAGE: dbumi.sql is a reference/installation artifact. It is not applied
-- by database/migrate.php. Apply CORE via the migration runner
-- (php database/migrate.php) for a database that already has Pharmacy, or
-- import dbumi.sql directly for a fresh combined install:
--   mysql --default-character-set=utf8mb4 -u <user> -p <database> < database/dbumi.sql
-- Tested against a live MariaDB 10.4.28 server in Phase 6 — see
-- docs/DBUMI-VALIDATION-REPORT.md. The explicit SET NAMES below is required:
-- importing this file with a plain `mysql < dbumi.sql` (no charset flag) was
-- verified in Phase 6 to silently corrupt every non-ASCII seeded value
-- (currency symbols, Arabic/Chinese language names) without it, because the
-- client then negotiates some other default charset for the session. This
-- statement makes a correct import happen regardless of client defaults.
-- ============================================================================

SET NAMES utf8mb4;

-- ============================================================================
-- SECTION 1: CORE — shared platform schema
-- ============================================================================

CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    business_name VARCHAR(190) DEFAULT NULL,
    email VARCHAR(190) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    timezone VARCHAR(100) NOT NULL DEFAULT 'Africa/Douala',
    currency_code CHAR(3) DEFAULT NULL,
    locale VARCHAR(20) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenants_uuid_unique (uuid),
    UNIQUE KEY tenants_slug_unique (slug),
    KEY tenants_status_index (status),
    KEY tenants_owner_index (owner_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(150) NOT NULL,
    setting_value LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenant_settings_tenant_key_unique (tenant_id, setting_key),
    CONSTRAINT tenant_settings_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_modules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    module_slug VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    configuration LONGTEXT DEFAULT NULL,
    enabled_at DATETIME DEFAULT NULL,
    disabled_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenant_modules_tenant_module_unique (tenant_id, module_slug),
    KEY tenant_modules_status_index (status),
    CONSTRAINT tenant_modules_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    uuid CHAR(36) NOT NULL,
    username VARCHAR(100) DEFAULT NULL,
    email VARCHAR(190) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    email_verified_at DATETIME DEFAULT NULL,
    last_login_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY users_uuid_unique (uuid),
    UNIQUE KEY users_username_unique (username),
    UNIQUE KEY users_email_unique (email),
    KEY users_status_index (status),
    KEY users_tenant_index (tenant_id),
    CONSTRAINT users_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE tenants
    ADD CONSTRAINT tenants_owner_foreign
        FOREIGN KEY (owner_user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    first_name VARCHAR(100) DEFAULT NULL,
    last_name VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    profile_image_path VARCHAR(255) DEFAULT NULL,
    address LONGTEXT DEFAULT NULL,
    locale VARCHAR(20) DEFAULT NULL,
    timezone VARCHAR(100) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY user_profiles_user_unique (user_id),
    CONSTRAINT user_profiles_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    session_token_hash CHAR(64) NOT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(1000) DEFAULT NULL,
    device_label VARCHAR(255) DEFAULT NULL,
    last_activity_at DATETIME DEFAULT NULL,
    expires_at DATETIME NOT NULL,
    revoked_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY user_sessions_uuid_unique (uuid),
    UNIQUE KEY user_sessions_token_hash_unique (session_token_hash),
    KEY user_sessions_user_active_index (user_id, revoked_at, expires_at),
    KEY user_sessions_tenant_index (tenant_id),
    CONSTRAINT user_sessions_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_sessions_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    description TEXT DEFAULT NULL,
    is_system_role TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    KEY roles_tenant_slug_index (tenant_id, slug),
    CONSTRAINT roles_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY permissions_slug_unique (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT UNSIGNED NOT NULL,
    permission_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT role_permissions_role_foreign
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT role_permissions_permission_foreign
        FOREIGN KEY (permission_id) REFERENCES permissions (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    assigned_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (user_id, role_id, tenant_id),
    KEY user_roles_tenant_index (tenant_id),
    CONSTRAINT user_roles_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_roles_role_foreign
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_roles_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_roles_assigned_by_foreign
        FOREIGN KEY (assigned_by) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS branches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL,
    email VARCHAR(190) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    address LONGTEXT DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY branches_tenant_code_unique (tenant_id, code),
    CONSTRAINT branches_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL,
    address LONGTEXT DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY warehouses_tenant_code_unique (tenant_id, code),
    KEY warehouses_branch_index (branch_id),
    CONSTRAINT warehouses_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT warehouses_branch_foreign
        FOREIGN KEY (branch_id) REFERENCES branches (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    login_identifier VARCHAR(190) DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(1000) DEFAULT NULL,
    was_successful TINYINT(1) NOT NULL DEFAULT 0,
    attempted_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY login_attempts_user_index (user_id),
    KEY login_attempts_identifier_index (login_identifier),
    KEY login_attempts_ip_index (ip_address),
    CONSTRAINT login_attempts_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    event_name VARCHAR(190) NOT NULL,
    subject_type VARCHAR(190) DEFAULT NULL,
    subject_id BIGINT UNSIGNED DEFAULT NULL,
    metadata LONGTEXT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY activity_logs_tenant_created_index (tenant_id, created_at),
    KEY activity_logs_user_created_index (user_id, created_at),
    CONSTRAINT activity_logs_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT activity_logs_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(190) NOT NULL,
    entity_id BIGINT UNSIGNED DEFAULT NULL,
    previous_values LONGTEXT DEFAULT NULL,
    new_values LONGTEXT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY audit_logs_tenant_created_index (tenant_id, created_at),
    KEY audit_logs_entity_index (entity_type, entity_id),
    CONSTRAINT audit_logs_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT audit_logs_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    notification_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body LONGTEXT DEFAULT NULL,
    data LONGTEXT DEFAULT NULL,
    read_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY notifications_user_read_index (user_id, read_at),
    KEY notifications_tenant_created_index (tenant_id, created_at),
    CONSTRAINT notifications_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT notifications_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY notification_preferences_user_type_channel_unique (user_id, notification_type, channel),
    CONSTRAINT notification_preferences_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_key VARCHAR(150) NOT NULL,
    setting_value LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY system_settings_key_unique (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    code VARCHAR(100) NOT NULL,
    provider VARCHAR(100) DEFAULT NULL,
    type VARCHAR(30) NOT NULL DEFAULT 'other',
    country_code CHAR(2) DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    configuration LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY payment_methods_code_unique (code),
    KEY payment_methods_tenant_code_index (tenant_id, code),
    CONSTRAINT payment_methods_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS currencies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(3) NOT NULL,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) DEFAULT NULL,
    countries VARCHAR(500) DEFAULT NULL,
    symbol_position VARCHAR(10) NOT NULL DEFAULT 'before',
    thousands_separator CHAR(1) NOT NULL DEFAULT ',',
    decimal_separator CHAR(1) NOT NULL DEFAULT '.',
    decimal_places TINYINT UNSIGNED NOT NULL DEFAULT 2,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY currencies_code_unique (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS languages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100) DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY languages_code_unique (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schema_migrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    migration VARCHAR(255) NOT NULL,
    batch INT UNSIGNED NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY schema_migrations_migration_unique (migration)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Phase 5 financial tables — identical to
-- database/migrations/0003_financial_foundation.sql. See that file's
-- header for the full design reasoning (one global catalog, tenant/branch
-- enablement tables, original-amount-never-overwritten payments).

CREATE TABLE IF NOT EXISTS tenant_currency_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    currency_id BIGINT UNSIGNED NOT NULL,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenant_currency_settings_tenant_currency_unique (tenant_id, currency_id),
    KEY tenant_currency_settings_currency_index (currency_id),
    CONSTRAINT tenant_currency_settings_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT tenant_currency_settings_currency_foreign
        FOREIGN KEY (currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_currency_preferences (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    currency_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY user_currency_preferences_user_tenant_unique (user_id, tenant_id),
    KEY user_currency_preferences_currency_index (currency_id),
    CONSTRAINT user_currency_preferences_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_currency_preferences_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_currency_preferences_currency_foreign
        FOREIGN KEY (currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Display-only. Setting a preference here must never change a stored payments.amount/currency_id.';

CREATE TABLE IF NOT EXISTS exchange_rates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    base_currency_id BIGINT UNSIGNED NOT NULL,
    quote_currency_id BIGINT UNSIGNED NOT NULL,
    rate DECIMAL(20,8) NOT NULL,
    source VARCHAR(100) DEFAULT NULL,
    effective_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY exchange_rates_pair_effective_index (base_currency_id, quote_currency_id, effective_at),
    CONSTRAINT exchange_rates_base_currency_foreign
        FOREIGN KEY (base_currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT exchange_rates_quote_currency_foreign
        FOREIGN KEY (quote_currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_payment_methods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    payment_method_id BIGINT UNSIGNED NOT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    configuration LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenant_payment_methods_tenant_method_unique (tenant_id, payment_method_id),
    KEY tenant_payment_methods_method_index (payment_method_id),
    CONSTRAINT tenant_payment_methods_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT tenant_payment_methods_method_foreign
        FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Only one row per tenant should have is_default=1; enforced in core/payments, not by a DB constraint.';

CREATE TABLE IF NOT EXISTS branch_payment_methods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    branch_id BIGINT UNSIGNED NOT NULL,
    payment_method_id BIGINT UNSIGNED NOT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY branch_payment_methods_branch_method_unique (branch_id, payment_method_id),
    KEY branch_payment_methods_method_index (payment_method_id),
    CONSTRAINT branch_payment_methods_branch_foreign
        FOREIGN KEY (branch_id) REFERENCES branches (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT branch_payment_methods_method_foreign
        FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='A branch can only further RESTRICT its tenant''s enabled methods; that parent relationship is enforced in core/payments, not by a DB constraint.';

CREATE TABLE IF NOT EXISTS payment_method_currencies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    payment_method_id BIGINT UNSIGNED NOT NULL,
    currency_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY payment_method_currencies_method_currency_unique (payment_method_id, currency_id),
    KEY payment_method_currencies_currency_index (currency_id),
    CONSTRAINT payment_method_currencies_method_foreign
        FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payment_method_currencies_currency_foreign
        FOREIGN KEY (currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cashier_shifts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED DEFAULT NULL,
    cashier_user_id BIGINT UNSIGNED NOT NULL,
    opening_currency_id BIGINT UNSIGNED NOT NULL,
    opening_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    expected_amount DECIMAL(14,2) DEFAULT NULL,
    counted_amount DECIMAL(14,2) DEFAULT NULL,
    difference_amount DECIMAL(14,2) DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    notes TEXT DEFAULT NULL,
    opened_at DATETIME NOT NULL,
    closed_at DATETIME DEFAULT NULL,
    reviewed_by BIGINT UNSIGNED DEFAULT NULL,
    reviewed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY cashier_shifts_uuid_unique (uuid),
    KEY cashier_shifts_tenant_status_index (tenant_id, status),
    KEY cashier_shifts_cashier_index (cashier_user_id, status),
    KEY cashier_shifts_branch_index (branch_id),
    CONSTRAINT cashier_shifts_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT cashier_shifts_branch_foreign
        FOREIGN KEY (branch_id) REFERENCES branches (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT cashier_shifts_cashier_foreign
        FOREIGN KEY (cashier_user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT cashier_shifts_opening_currency_foreign
        FOREIGN KEY (opening_currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT cashier_shifts_reviewed_by_foreign
        FOREIGN KEY (reviewed_by) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='"Only one open shift per cashier at a time" is an application rule (core/payments/cashier-shift-service.php), not a DB constraint — MySQL cannot express a partial unique index cleanly.';

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED DEFAULT NULL,
    cashier_shift_id BIGINT UNSIGNED DEFAULT NULL,
    reference_type VARCHAR(100) DEFAULT NULL,
    reference_id BIGINT UNSIGNED DEFAULT NULL,
    customer_reference_type VARCHAR(100) DEFAULT NULL,
    customer_reference_id BIGINT UNSIGNED DEFAULT NULL,
    customer_display_name VARCHAR(190) DEFAULT NULL,
    cashier_user_id BIGINT UNSIGNED DEFAULT NULL,
    salesperson_user_id BIGINT UNSIGNED DEFAULT NULL,
    payment_method_id BIGINT UNSIGNED NOT NULL,
    currency_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    base_currency_id BIGINT UNSIGNED DEFAULT NULL,
    base_amount DECIMAL(14,2) DEFAULT NULL,
    exchange_rate DECIMAL(20,8) DEFAULT NULL,
    exchange_rate_recorded_at DATETIME DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    transaction_reference VARCHAR(190) DEFAULT NULL,
    provider_reference VARCHAR(190) DEFAULT NULL,
    receipt_number VARCHAR(100) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY payments_uuid_unique (uuid),
    KEY payments_tenant_created_index (tenant_id, created_at),
    KEY payments_branch_created_index (branch_id, created_at),
    KEY payments_cashier_index (cashier_user_id),
    KEY payments_salesperson_index (salesperson_user_id),
    KEY payments_method_index (payment_method_id),
    KEY payments_currency_index (currency_id),
    KEY payments_reference_index (reference_type, reference_id),
    KEY payments_customer_reference_index (customer_reference_type, customer_reference_id),
    KEY payments_shift_index (cashier_shift_id),
    KEY payments_status_index (status),
    CONSTRAINT payments_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_branch_foreign
        FOREIGN KEY (branch_id) REFERENCES branches (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_shift_foreign
        FOREIGN KEY (cashier_shift_id) REFERENCES cashier_shifts (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_cashier_foreign
        FOREIGN KEY (cashier_user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_salesperson_foreign
        FOREIGN KEY (salesperson_user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_method_foreign
        FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_currency_foreign
        FOREIGN KEY (currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payments_base_currency_foreign
        FOREIGN KEY (base_currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='amount/currency_id are the original transaction truth and must never be overwritten; base_amount/exchange_rate are a derived, simultaneously-stored conversion, not a replacement.';

CREATE TABLE IF NOT EXISTS payment_refunds (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    payment_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    currency_id BIGINT UNSIGNED NOT NULL,
    reason TEXT DEFAULT NULL,
    refunded_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY payment_refunds_uuid_unique (uuid),
    KEY payment_refunds_payment_index (payment_id),
    CONSTRAINT payment_refunds_payment_foreign
        FOREIGN KEY (payment_id) REFERENCES payments (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payment_refunds_currency_foreign
        FOREIGN KEY (currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT payment_refunds_refunded_by_foreign
        FOREIGN KEY (refunded_by) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS financial_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    default_currency_id BIGINT UNSIGNED NOT NULL,
    default_payment_method_id BIGINT UNSIGNED DEFAULT NULL,
    allow_employee_currency_preference TINYINT(1) NOT NULL DEFAULT 0,
    require_shift_for_cashier TINYINT(1) NOT NULL DEFAULT 1,
    base_currency_locked TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY financial_settings_tenant_unique (tenant_id),
    CONSTRAINT financial_settings_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT financial_settings_default_currency_foreign
        FOREIGN KEY (default_currency_id) REFERENCES currencies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT financial_settings_default_method_foreign
        FOREIGN KEY (default_payment_method_id) REFERENCES payment_methods (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CORE seed data (shared permission catalog, currencies, languages) —
-- identical to database/migrations/0002_identity_foundation.sql.

INSERT IGNORE INTO permissions (name, slug, description, created_at) VALUES
    ('View products', 'products.view', 'View product records', NOW()),
    ('Create products', 'products.create', 'Create product records', NOW()),
    ('Edit products', 'products.edit', 'Edit product records', NOW()),
    ('Delete products', 'products.delete', 'Delete product records', NOW()),
    ('View sales', 'sales.view', 'View sales records', NOW()),
    ('Create sales', 'sales.create', 'Create sales records', NOW()),
    ('Edit sales', 'sales.edit', 'Edit sales records', NOW()),
    ('Delete sales', 'sales.delete', 'Delete sales records', NOW()),
    ('Confirm sales', 'sales.confirm', 'Confirm or finalize a sale', NOW()),
    ('View payments', 'payments.view', 'View payment records', NOW()),
    ('Create payments', 'payments.create', 'Record a payment', NOW()),
    ('Confirm payments', 'payments.confirm', 'Confirm a recorded payment', NOW()),
    ('Refund payments', 'payments.refund', 'Issue a payment refund', NOW()),
    ('View stock', 'stock.view', 'View stock levels', NOW()),
    ('Adjust stock', 'stock.adjust', 'Manually adjust stock quantities', NOW()),
    ('Transfer stock', 'stock.transfer', 'Transfer stock between branches or warehouses', NOW()),
    ('Record stock damage', 'stock.damage', 'Record damaged or written-off stock', NOW()),
    ('View reports', 'reports.view', 'View reports', NOW()),
    ('Export reports', 'reports.export', 'Export report data', NOW()),
    ('View users', 'users.view', 'View user accounts', NOW()),
    ('Create users', 'users.create', 'Create user accounts', NOW()),
    ('Edit users', 'users.edit', 'Edit user accounts', NOW()),
    ('Delete users', 'users.delete', 'Delete user accounts', NOW()),
    ('View settings', 'settings.view', 'View tenant settings', NOW()),
    ('Edit settings', 'settings.edit', 'Edit tenant settings', NOW());

INSERT IGNORE INTO currencies (code, name, symbol, decimal_places, is_active, created_at) VALUES
    ('XAF', 'Central African CFA Franc', 'FCFA', 0, 1, NOW()),
    ('XOF', 'West African CFA Franc', 'CFA', 0, 1, NOW()),
    ('NGN', 'Nigerian Naira', 'NGN', 2, 1, NOW()),
    ('GHS', 'Ghanaian Cedi', 'GHS', 2, 1, NOW()),
    ('KES', 'Kenyan Shilling', 'KSh', 2, 1, NOW()),
    ('ZAR', 'South African Rand', 'R', 2, 1, NOW()),
    ('EGP', 'Egyptian Pound', 'E£', 2, 1, NOW()),
    ('USD', 'US Dollar', '$', 2, 1, NOW()),
    ('EUR', 'Euro', '€', 2, 1, NOW());

INSERT IGNORE INTO languages (code, name, native_name, is_active, created_at) VALUES
    ('en', 'English', 'English', 1, NOW()),
    ('fr', 'French', 'Français', 1, NOW()),
    ('ar', 'Arabic', 'العربية', 0, NOW()),
    ('pt', 'Portuguese', 'Português', 0, NOW()),
    ('sw', 'Swahili', 'Kiswahili', 0, NOW()),
    ('ha', 'Hausa', 'Hausa', 0, NOW()),
    ('es', 'Spanish', 'Español', 0, NOW()),
    ('zh', 'Chinese (Simplified)', '中文', 0, NOW());

-- Phase 5 seed data — identical to
-- database/migrations/0003_financial_foundation.sql. See that file for
-- the full ISO-4217-verification and currency-restriction notes.

INSERT IGNORE INTO permissions (name, slug, description, created_at) VALUES
    ('Manage payment methods', 'payment_methods.manage', 'Enable/disable and configure tenant payment methods', NOW()),
    ('Manage currency settings', 'currencies.manage', 'Enable currencies and set the tenant default currency', NOW()),
    ('Open cashier shift', 'cashier_shifts.open', 'Open a cashier shift', NOW()),
    ('Close cashier shift', 'cashier_shifts.close', 'Close a cashier shift and enter counted cash', NOW()),
    ('Review cashier shift', 'cashier_shifts.review', 'Review a closed cashier shift and its cash difference', NOW()),
    ('Issue payment refunds', 'payments.refund_issue', 'Issue a refund against a recorded payment', NOW());

INSERT IGNORE INTO currencies (code, name, symbol, decimal_places, is_active, countries, created_at) VALUES
    ('GMD', 'Gambian Dalasi', 'D', 2, 1, 'Gambia', NOW()),
    ('GNF', 'Guinean Franc', 'FG', 0, 1, 'Guinea', NOW()),
    ('SLE', 'Sierra Leonean Leone', 'Le', 2, 1, 'Sierra Leone', NOW()),
    ('LRD', 'Liberian Dollar', 'L$', 2, 1, 'Liberia', NOW()),
    ('MRU', 'Mauritanian Ouguiya', 'UM', 2, 1, 'Mauritania', NOW()),
    ('CVE', 'Cape Verdean Escudo', 'Esc', 2, 1, 'Cabo Verde', NOW()),
    ('MAD', 'Moroccan Dirham', 'DH', 2, 1, 'Morocco', NOW()),
    ('DZD', 'Algerian Dinar', 'DA', 2, 1, 'Algeria', NOW()),
    ('TND', 'Tunisian Dinar', 'DT', 3, 1, 'Tunisia', NOW()),
    ('SDG', 'Sudanese Pound', 'SDG', 2, 1, 'Sudan', NOW()),
    ('SSP', 'South Sudanese Pound', 'SSP', 2, 1, 'South Sudan', NOW()),
    ('ETB', 'Ethiopian Birr', 'Br', 2, 1, 'Ethiopia', NOW()),
    ('DJF', 'Djiboutian Franc', 'Fdj', 0, 1, 'Djibouti', NOW()),
    ('SOS', 'Somali Shilling', 'Sh', 2, 1, 'Somalia', NOW()),
    ('UGX', 'Ugandan Shilling', 'USh', 0, 1, 'Uganda', NOW()),
    ('TZS', 'Tanzanian Shilling', 'TSh', 2, 1, 'Tanzania', NOW()),
    ('RWF', 'Rwandan Franc', 'FRw', 0, 1, 'Rwanda', NOW()),
    ('BIF', 'Burundian Franc', 'FBu', 0, 1, 'Burundi', NOW()),
    ('CDF', 'Congolese Franc', 'FC', 2, 1, 'Democratic Republic of the Congo', NOW()),
    ('AOA', 'Angolan Kwanza', 'Kz', 2, 1, 'Angola', NOW()),
    ('ZMW', 'Zambian Kwacha', 'ZK', 2, 1, 'Zambia', NOW()),
    ('MWK', 'Malawian Kwacha', 'MK', 2, 1, 'Malawi', NOW()),
    ('MZN', 'Mozambican Metical', 'MT', 2, 1, 'Mozambique', NOW()),
    ('BWP', 'Botswana Pula', 'P', 2, 1, 'Botswana', NOW()),
    ('NAD', 'Namibian Dollar', 'N$', 2, 1, 'Namibia', NOW()),
    ('SZL', 'Eswatini Lilangeni', 'E', 2, 1, 'Eswatini', NOW()),
    ('LSL', 'Lesotho Loti', 'L', 2, 1, 'Lesotho', NOW()),
    ('MUR', 'Mauritian Rupee', 'Rs', 2, 1, 'Mauritius', NOW()),
    ('SCR', 'Seychellois Rupee', 'SR', 2, 1, 'Seychelles', NOW()),
    ('KMF', 'Comorian Franc', 'CF', 0, 1, 'Comoros', NOW()),
    ('MGA', 'Malagasy Ariary', 'Ar', 2, 1, 'Madagascar', NOW()),
    ('STN', 'São Tomé and Príncipe Dobra', 'Db', 2, 1, 'São Tomé and Príncipe', NOW()),
    ('ERN', 'Eritrean Nakfa', 'Nfk', 2, 1, 'Eritrea', NOW()),
    ('ZWG', 'Zimbabwe Gold', 'ZiG', 2, 1, 'Zimbabwe', NOW()),
    ('GBP', 'British Pound Sterling', '£', 2, 1, 'United Kingdom', NOW()),
    ('CHF', 'Swiss Franc', 'Fr.', 2, 1, 'Switzerland', NOW()),
    ('CAD', 'Canadian Dollar', 'C$', 2, 1, 'Canada', NOW()),
    ('AUD', 'Australian Dollar', 'A$', 2, 1, 'Australia', NOW()),
    ('NZD', 'New Zealand Dollar', 'NZ$', 2, 1, 'New Zealand', NOW()),
    ('JPY', 'Japanese Yen', '¥', 0, 1, 'Japan', NOW()),
    ('CNY', 'Chinese Yuan', '¥', 2, 1, 'China', NOW()),
    ('HKD', 'Hong Kong Dollar', 'HK$', 2, 1, 'Hong Kong', NOW()),
    ('SGD', 'Singapore Dollar', 'S$', 2, 1, 'Singapore', NOW()),
    ('AED', 'UAE Dirham', 'د.إ', 2, 1, 'United Arab Emirates', NOW()),
    ('SAR', 'Saudi Riyal', '﷼', 2, 1, 'Saudi Arabia', NOW()),
    ('QAR', 'Qatari Riyal', '﷼', 2, 1, 'Qatar', NOW()),
    ('KWD', 'Kuwaiti Dinar', 'د.ك', 3, 1, 'Kuwait', NOW()),
    ('BHD', 'Bahraini Dinar', '.د.ب', 3, 1, 'Bahrain', NOW()),
    ('OMR', 'Omani Rial', '﷼', 3, 1, 'Oman', NOW()),
    ('INR', 'Indian Rupee', '₹', 2, 1, 'India', NOW()),
    ('PKR', 'Pakistani Rupee', '₨', 2, 1, 'Pakistan', NOW()),
    ('BDT', 'Bangladeshi Taka', '৳', 2, 1, 'Bangladesh', NOW()),
    ('TRY', 'Turkish Lira', '₺', 2, 1, 'Turkey', NOW()),
    ('BRL', 'Brazilian Real', 'R$', 2, 1, 'Brazil', NOW()),
    ('MXN', 'Mexican Peso', '$', 2, 1, 'Mexico', NOW()),
    ('RUB', 'Russian Ruble', '₽', 2, 1, 'Russia', NOW()),
    ('KRW', 'South Korean Won', '₩', 0, 1, 'South Korea', NOW()),
    ('THB', 'Thai Baht', '฿', 2, 1, 'Thailand', NOW()),
    ('MYR', 'Malaysian Ringgit', 'RM', 2, 1, 'Malaysia', NOW()),
    ('IDR', 'Indonesian Rupiah', 'Rp', 2, 1, 'Indonesia', NOW()),
    ('PHP', 'Philippine Peso', '₱', 2, 1, 'Philippines', NOW());

INSERT IGNORE INTO payment_methods (tenant_id, name, code, provider, type, country_code, is_active, created_at) VALUES
    (NULL, 'Cash', 'cash', NULL, 'cash', NULL, 1, NOW()),
    (NULL, 'Bank Transfer', 'bank_transfer', NULL, 'bank_transfer', NULL, 1, NOW()),
    (NULL, 'Bank Deposit', 'bank_deposit', NULL, 'bank_deposit', NULL, 1, NOW()),
    (NULL, 'Card', 'card', NULL, 'card', NULL, 1, NOW()),
    (NULL, 'Visa', 'visa', 'Visa', 'card', NULL, 1, NOW()),
    (NULL, 'Mastercard', 'mastercard', 'Mastercard', 'card', NULL, 1, NOW()),
    (NULL, 'Cheque', 'cheque', NULL, 'cheque', NULL, 1, NOW()),
    (NULL, 'Gift Card', 'gift_card', NULL, 'gift_card', NULL, 1, NOW()),
    (NULL, 'Store Credit', 'store_credit', NULL, 'store_credit', NULL, 1, NOW()),
    (NULL, 'Account / Credit', 'customer_account', NULL, 'customer_account', NULL, 1, NOW()),
    (NULL, 'Other', 'other', NULL, 'other', NULL, 1, NOW()),
    (NULL, 'MTN Mobile Money', 'mtn_momo_cm', 'MTN', 'mobile_money', 'CM', 1, NOW()),
    (NULL, 'Orange Money', 'orange_money_cm', 'Orange', 'mobile_money', 'CM', 1, NOW()),
    (NULL, 'Express Union Mobile Money', 'express_union', 'Express Union', 'mobile_money', 'CM', 1, NOW()),
    (NULL, 'Yoomee Money', 'yoomee_money', 'Yoomee', 'mobile_money', 'CM', 1, NOW()),
    (NULL, 'M-Pesa', 'mpesa', 'Safaricom', 'mobile_money', 'KE', 1, NOW()),
    (NULL, 'Airtel Money', 'airtel_money', 'Airtel', 'mobile_money', NULL, 1, NOW()),
    (NULL, 'Vodafone Cash', 'vodafone_cash', 'Vodafone', 'mobile_money', 'GH', 1, NOW()),
    (NULL, 'Moov Money', 'moov_money', 'Moov', 'mobile_money', NULL, 1, NOW()),
    (NULL, 'Wave', 'wave', 'Wave', 'mobile_money', NULL, 1, NOW()),
    (NULL, 'Tigo Cash', 'tigo_cash', 'Tigo', 'mobile_money', 'TZ', 1, NOW()),
    (NULL, 'EcoCash', 'ecocash', 'Econet', 'mobile_money', 'ZW', 1, NOW()),
    (NULL, 'Telebirr', 'telebirr', 'Ethio Telecom', 'mobile_money', 'ET', 1, NOW()),
    (NULL, 'Chipper Cash', 'chipper_cash', 'Chipper Cash', 'digital_wallet', NULL, 1, NOW());

INSERT IGNORE INTO payment_method_currencies (payment_method_id, currency_id, created_at)
SELECT pm.id, c.id, NOW() FROM payment_methods pm
INNER JOIN currencies c ON (
    (pm.code = 'mtn_momo_cm' AND c.code = 'XAF') OR
    (pm.code = 'orange_money_cm' AND c.code = 'XAF') OR
    (pm.code = 'express_union' AND c.code = 'XAF') OR
    (pm.code = 'yoomee_money' AND c.code = 'XAF') OR
    (pm.code = 'mpesa' AND c.code = 'KES') OR
    (pm.code = 'vodafone_cash' AND c.code = 'GHS') OR
    (pm.code = 'tigo_cash' AND c.code = 'TZS') OR
    (pm.code = 'ecocash' AND c.code = 'ZWG') OR
    (pm.code = 'telebirr' AND c.code = 'ETB') OR
    (pm.code = 'chipper_cash' AND c.code IN ('NGN', 'GHS', 'KES', 'UGX', 'ZAR'))
)
WHERE pm.tenant_id IS NULL;


-- ============================================================================
-- SECTION 2: PHARMACY MODULE — legacy schema (unmodified, see the header)
-- ============================================================================
-- Source: management/pharmacy/database/db.sql / root db.sql. The
-- CREATE DATABASE, USE, and DROP TABLE IF EXISTS statements from that
-- standalone file are intentionally omitted here — dbumi.sql is one shared
-- database, and these tables must not be dropped when other sections of
-- this file are (re-)applied.

CREATE TABLE `store` (
  `store_id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(100) UNIQUE NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `city` VARCHAR(100) DEFAULT 'Cameroon',
  `country` VARCHAR(100) DEFAULT 'Cameroon',
  `currency` VARCHAR(10) DEFAULT 'XAF',
  `store_status` VARCHAR(50) DEFAULT 'active',
  `registration_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME,
  UNIQUE KEY `unique_username` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_method` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `method_name` VARCHAR(100) NOT NULL,
  `method_code` VARCHAR(50) UNIQUE NOT NULL,
  `category` VARCHAR(50) DEFAULT 'mobile_money',
  `is_active` TINYINT DEFAULT 1,
  `description` TEXT,
  `date_added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_customer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `customertype` VARCHAR(50) DEFAULT 'Regular',
  `customerstatus` VARCHAR(50) DEFAULT 'active',
  `points` INT DEFAULT 0,
  `due` DECIMAL(10,2) DEFAULT 0,
  `wallet` DECIMAL(10,2) DEFAULT 0,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_supplier` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `receivable` DECIMAL(10,2) DEFAULT 0,
  `payable` DECIMAL(10,2) DEFAULT 0,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_medicine_category` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `img` VARCHAR(255),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_brand` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `details` TEXT,
  `img` VARCHAR(255),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `medicine_unit` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `unit` VARCHAR(50) NOT NULL UNIQUE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `medicine_type` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `type` VARCHAR(50) NOT NULL UNIQUE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_medicine` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `expiredate` DATE,
  `abroad` VARCHAR(50),
  `name` VARCHAR(200) NOT NULL,
  `details` TEXT,
  `category` INT,
  `brand` INT,
  `strength` VARCHAR(100),
  `unit` INT,
  `code` VARCHAR(100) UNIQUE,
  `shelf` VARCHAR(100),
  `cost` DECIMAL(10,2) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `qty` INT DEFAULT 0,
  `img` VARCHAR(255),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`category`) REFERENCES `p_medicine_category`(`id`),
  FOREIGN KEY (`brand`) REFERENCES `p_brand`(`id`),
  FOREIGN KEY (`unit`) REFERENCES `medicine_unit`(`id`),
  INDEX `idx_store` (`store`),
  INDEX `idx_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_supply` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `title` VARCHAR(200),
  `supplier` INT,
  `total` DECIMAL(10,2),
  `payable` DECIMAL(10,2),
  `paid` DECIMAL(10,2),
  `due` DECIMAL(10,2),
  `details` TEXT,
  `supplydate` DATE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`supplier`) REFERENCES `p_supplier`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_purchase_summary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100) UNIQUE,
  `store` INT NOT NULL,
  `total_qty` INT,
  `total_price` DECIMAL(12,2),
  `total_cost` DECIMAL(12,2),
  `payment_method` VARCHAR(100),
  `coupon` VARCHAR(100),
  `discounted` DECIMAL(10,2) DEFAULT 0,
  `payable` DECIMAL(12,2),
  `paid_status` VARCHAR(50) DEFAULT 'pending',
  `transection_id` VARCHAR(100),
  `transection_submit_date` DATETIME,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_purchase` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100),
  `store` INT NOT NULL,
  `product_id` INT,
  `product` VARCHAR(200),
  `qty` INT,
  `cost` DECIMAL(10,2),
  `totalcost` DECIMAL(12,2),
  `price` DECIMAL(10,2),
  `totalprice` DECIMAL(12,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_invoice_summary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100) UNIQUE,
  `store` INT NOT NULL,
  `client` VARCHAR(100),
  `total_qty` INT,
  `total_price` DECIMAL(12,2),
  `total_cost` DECIMAL(12,2),
  `payment_method` VARCHAR(100),
  `paid` DECIMAL(12,2),
  `due` DECIMAL(12,2),
  `discount_type` VARCHAR(10),
  `discount` DECIMAL(10,2) DEFAULT 0,
  `payable` DECIMAL(12,2),
  `order_date` DATETIME,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_invoice` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100),
  `store` INT NOT NULL,
  `product_id` INT,
  `product` VARCHAR(200),
  `qty` INT,
  `cost` DECIMAL(10,2),
  `totalcost` DECIMAL(12,2),
  `price` DECIMAL(10,2),
  `totalprice` DECIMAL(12,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_return_summary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `invoice` VARCHAR(100),
  `customer` VARCHAR(100),
  `customer_id` INT,
  `grand_price` DECIMAL(12,2),
  `customer_paid` DECIMAL(12,2),
  `returnable` DECIMAL(12,2),
  `returned` DECIMAL(12,2),
  `discount` DECIMAL(10,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `p_customer`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_return_product` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `return_id` INT,
  `product_id` INT,
  `product_name` VARCHAR(200),
  `qty` INT,
  `price` DECIMAL(10,2),
  `total` DECIMAL(12,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`return_id`) REFERENCES `p_return_summary`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_damage_product` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `product` INT,
  `total_qty` INT,
  `damage_qty` INT,
  `cost` DECIMAL(10,2),
  `price` DECIMAL(10,2),
  `note` TEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_payment` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `transaction` VARCHAR(100),
  `payment_date` DATE,
  `payment_type` VARCHAR(50),
  `account_type` VARCHAR(50),
  `name` VARCHAR(100),
  `phone` VARCHAR(20),
  `amount` DECIMAL(12,2),
  `payment_method` VARCHAR(100),
  `details` TEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_payment_date` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_expense_category` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_expense` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `category` INT,
  `amount` DECIMAL(12,2),
  `details` TEXT,
  `expense_date` DATE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`category`) REFERENCES `p_expense_category`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cart` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user` INT NOT NULL,
  `product_id` INT,
  `product_name` VARCHAR(200),
  `qty` INT DEFAULT 1,
  `price` DECIMAL(10,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`user`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_user` (`user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `return_cart` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `product_id` INT,
  `product_name` VARCHAR(200),
  `qty` INT DEFAULT 1,
  `price` DECIMAL(10,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_store_active ON `store`(`store_status`);
CREATE INDEX idx_registration ON `store`(`registration_date`);
CREATE INDEX idx_medicine_store ON `p_medicine`(`store`);
CREATE INDEX idx_medicine_category ON `p_medicine`(`category`);
CREATE INDEX idx_invoice_store ON `p_invoice_summary`(`store`, `order_date`);
CREATE INDEX idx_purchase_store ON `p_purchase_summary`(`store`, `date`);

-- ============================================================================
-- END dbumi.sql — CORE (through Phase 5) + PHARMACY MODULE
-- ============================================================================
