-- ============================================================================
-- THERAIN UNIFIED — COMPLETE (dbumi) DATABASE
-- ============================================================================
-- dbumi.sql = CORE (shared platform schema) + the schema of every ENABLED
-- management module, combined. As of Phase 4, Pharmacy is the only enabled
-- module (modules/manifest.php), so this file currently contains:
--
--   1. CORE   — the shared identity/platform schema, equivalent to applying
--                database/migrations/0001_initial_unified_schema.sql and
--                0002_identity_foundation.sql to an empty database (the two
--                ALTER TABLE columns from 0002 are written directly into
--                their CREATE TABLE statements here, since this file
--                represents a fresh-install target state, not a migration
--                history).
--   2. PHARMACY MODULE — the unmodified legacy Pharmacy schema, identical to
--                management/pharmacy/database/db.sql (minus its own
--                CREATE DATABASE/USE/DROP statements, which do not apply
--                inside a shared database).
--
-- IMPORTANT — KNOWN, DOCUMENTED INCONSISTENCY:
-- CORE and PHARMACY MODULE are two coexisting, NOT YET CROSS-REFERENCED
-- identity systems. CORE uses tenants/users/branches; Pharmacy still uses
-- its own `store` table and store_id. No foreign key connects them. This
-- is intentional and matches every prior phase's compatibility decision
-- (see docs/AUTHENTICATION-ARCHITECTURE.md, docs/TENANT-ARCHITECTURE.md).
-- Reconciling them is a separate, later, audited migration — see
-- docs/PHARMACY-DATABASE-MIGRATION-PLAN.md. Do not treat this file as
-- evidence that Pharmacy has been integrated into the tenant model.
--
-- MAINTENANCE (manual, reviewed process — see docs/DBUMI-ARCHITECTURE.md):
-- This file is hand-composed and hand-reviewed, not generated by an
-- automatic build script. When a new module is enabled in
-- modules/manifest.php, its management/<slug>/database/db.sql content is
-- reviewed for table-name collisions against every existing section, then
-- appended here as a new section, and this header is updated. There is no
-- tool that runs this automatically; that is a deliberate choice to avoid
-- silently concatenating unreviewed SQL into a database file relied upon by
-- real installations.
--
-- USAGE: dbumi.sql is a reference/installation artifact. It is not applied
-- by database/migrate.php. Apply CORE via the migration runner
-- (php database/migrate.php) for a database that already has Pharmacy, or
-- import dbumi.sql directly for a fresh combined install. NOT TESTED
-- against a live MySQL/MariaDB server in this workspace — see
-- docs/PHASE-4-REPORT.md.
-- ============================================================================


-- ============================================================================
-- SECTION 1: CORE — shared platform schema
-- ============================================================================

CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    business_name VARCHAR(190) DEFAULT NULL,
    email VARCHAR(190) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    timezone VARCHAR(100) NOT NULL DEFAULT 'Africa/Douala',
    currency_code CHAR(3) DEFAULT NULL,
    locale VARCHAR(20) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenants_uuid_unique (uuid),
    UNIQUE KEY tenants_slug_unique (slug),
    KEY tenants_status_index (status),
    KEY tenants_owner_index (owner_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(150) NOT NULL,
    setting_value LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenant_settings_tenant_key_unique (tenant_id, setting_key),
    CONSTRAINT tenant_settings_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_modules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    module_slug VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    configuration LONGTEXT DEFAULT NULL,
    enabled_at DATETIME DEFAULT NULL,
    disabled_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY tenant_modules_tenant_module_unique (tenant_id, module_slug),
    KEY tenant_modules_status_index (status),
    CONSTRAINT tenant_modules_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    uuid CHAR(36) NOT NULL,
    username VARCHAR(100) DEFAULT NULL,
    email VARCHAR(190) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    email_verified_at DATETIME DEFAULT NULL,
    last_login_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY users_uuid_unique (uuid),
    UNIQUE KEY users_username_unique (username),
    UNIQUE KEY users_email_unique (email),
    KEY users_status_index (status),
    KEY users_tenant_index (tenant_id),
    CONSTRAINT users_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE tenants
    ADD CONSTRAINT tenants_owner_foreign
        FOREIGN KEY (owner_user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    first_name VARCHAR(100) DEFAULT NULL,
    last_name VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    profile_image_path VARCHAR(255) DEFAULT NULL,
    address LONGTEXT DEFAULT NULL,
    locale VARCHAR(20) DEFAULT NULL,
    timezone VARCHAR(100) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY user_profiles_user_unique (user_id),
    CONSTRAINT user_profiles_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    session_token_hash CHAR(64) NOT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(1000) DEFAULT NULL,
    device_label VARCHAR(255) DEFAULT NULL,
    last_activity_at DATETIME DEFAULT NULL,
    expires_at DATETIME NOT NULL,
    revoked_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY user_sessions_uuid_unique (uuid),
    UNIQUE KEY user_sessions_token_hash_unique (session_token_hash),
    KEY user_sessions_user_active_index (user_id, revoked_at, expires_at),
    KEY user_sessions_tenant_index (tenant_id),
    CONSTRAINT user_sessions_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_sessions_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    description TEXT DEFAULT NULL,
    is_system_role TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    KEY roles_tenant_slug_index (tenant_id, slug),
    CONSTRAINT roles_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY permissions_slug_unique (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT UNSIGNED NOT NULL,
    permission_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT role_permissions_role_foreign
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT role_permissions_permission_foreign
        FOREIGN KEY (permission_id) REFERENCES permissions (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    assigned_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (user_id, role_id, tenant_id),
    KEY user_roles_tenant_index (tenant_id),
    CONSTRAINT user_roles_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_roles_role_foreign
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_roles_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT user_roles_assigned_by_foreign
        FOREIGN KEY (assigned_by) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS branches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL,
    email VARCHAR(190) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    address LONGTEXT DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY branches_tenant_code_unique (tenant_id, code),
    CONSTRAINT branches_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    branch_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL,
    address LONGTEXT DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY warehouses_tenant_code_unique (tenant_id, code),
    KEY warehouses_branch_index (branch_id),
    CONSTRAINT warehouses_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT warehouses_branch_foreign
        FOREIGN KEY (branch_id) REFERENCES branches (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    login_identifier VARCHAR(190) DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(1000) DEFAULT NULL,
    was_successful TINYINT(1) NOT NULL DEFAULT 0,
    attempted_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY login_attempts_user_index (user_id),
    KEY login_attempts_identifier_index (login_identifier),
    KEY login_attempts_ip_index (ip_address),
    CONSTRAINT login_attempts_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    event_name VARCHAR(190) NOT NULL,
    subject_type VARCHAR(190) DEFAULT NULL,
    subject_id BIGINT UNSIGNED DEFAULT NULL,
    metadata LONGTEXT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY activity_logs_tenant_created_index (tenant_id, created_at),
    KEY activity_logs_user_created_index (user_id, created_at),
    CONSTRAINT activity_logs_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT activity_logs_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(190) NOT NULL,
    entity_id BIGINT UNSIGNED DEFAULT NULL,
    previous_values LONGTEXT DEFAULT NULL,
    new_values LONGTEXT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY audit_logs_tenant_created_index (tenant_id, created_at),
    KEY audit_logs_entity_index (entity_type, entity_id),
    CONSTRAINT audit_logs_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT audit_logs_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    user_id BIGINT UNSIGNED DEFAULT NULL,
    notification_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body LONGTEXT DEFAULT NULL,
    data LONGTEXT DEFAULT NULL,
    read_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY notifications_user_read_index (user_id, read_at),
    KEY notifications_tenant_created_index (tenant_id, created_at),
    CONSTRAINT notifications_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT notifications_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY notification_preferences_user_type_channel_unique (user_id, notification_type, channel),
    CONSTRAINT notification_preferences_user_foreign
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_key VARCHAR(150) NOT NULL,
    setting_value LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY system_settings_key_unique (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    configuration LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    KEY payment_methods_tenant_code_index (tenant_id, code),
    CONSTRAINT payment_methods_tenant_foreign
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS currencies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(3) NOT NULL,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) DEFAULT NULL,
    decimal_places TINYINT UNSIGNED NOT NULL DEFAULT 2,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY currencies_code_unique (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS languages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100) DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY languages_code_unique (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schema_migrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    migration VARCHAR(255) NOT NULL,
    batch INT UNSIGNED NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY schema_migrations_migration_unique (migration)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CORE seed data (shared permission catalog, currencies, languages) —
-- identical to database/migrations/0002_identity_foundation.sql.

INSERT IGNORE INTO permissions (name, slug, description, created_at) VALUES
    ('View products', 'products.view', 'View product records', NOW()),
    ('Create products', 'products.create', 'Create product records', NOW()),
    ('Edit products', 'products.edit', 'Edit product records', NOW()),
    ('Delete products', 'products.delete', 'Delete product records', NOW()),
    ('View sales', 'sales.view', 'View sales records', NOW()),
    ('Create sales', 'sales.create', 'Create sales records', NOW()),
    ('Edit sales', 'sales.edit', 'Edit sales records', NOW()),
    ('Delete sales', 'sales.delete', 'Delete sales records', NOW()),
    ('Confirm sales', 'sales.confirm', 'Confirm or finalize a sale', NOW()),
    ('View payments', 'payments.view', 'View payment records', NOW()),
    ('Create payments', 'payments.create', 'Record a payment', NOW()),
    ('Confirm payments', 'payments.confirm', 'Confirm a recorded payment', NOW()),
    ('Refund payments', 'payments.refund', 'Issue a payment refund', NOW()),
    ('View stock', 'stock.view', 'View stock levels', NOW()),
    ('Adjust stock', 'stock.adjust', 'Manually adjust stock quantities', NOW()),
    ('Transfer stock', 'stock.transfer', 'Transfer stock between branches or warehouses', NOW()),
    ('Record stock damage', 'stock.damage', 'Record damaged or written-off stock', NOW()),
    ('View reports', 'reports.view', 'View reports', NOW()),
    ('Export reports', 'reports.export', 'Export report data', NOW()),
    ('View users', 'users.view', 'View user accounts', NOW()),
    ('Create users', 'users.create', 'Create user accounts', NOW()),
    ('Edit users', 'users.edit', 'Edit user accounts', NOW()),
    ('Delete users', 'users.delete', 'Delete user accounts', NOW()),
    ('View settings', 'settings.view', 'View tenant settings', NOW()),
    ('Edit settings', 'settings.edit', 'Edit tenant settings', NOW());

INSERT IGNORE INTO currencies (code, name, symbol, decimal_places, is_active, created_at) VALUES
    ('XAF', 'Central African CFA Franc', 'FCFA', 0, 1, NOW()),
    ('XOF', 'West African CFA Franc', 'CFA', 0, 1, NOW()),
    ('NGN', 'Nigerian Naira', 'NGN', 2, 1, NOW()),
    ('GHS', 'Ghanaian Cedi', 'GHS', 2, 1, NOW()),
    ('KES', 'Kenyan Shilling', 'KSh', 2, 1, NOW()),
    ('ZAR', 'South African Rand', 'R', 2, 1, NOW()),
    ('EGP', 'Egyptian Pound', 'E£', 2, 1, NOW()),
    ('USD', 'US Dollar', '$', 2, 1, NOW()),
    ('EUR', 'Euro', '€', 2, 1, NOW());

INSERT IGNORE INTO languages (code, name, native_name, is_active, created_at) VALUES
    ('en', 'English', 'English', 1, NOW()),
    ('fr', 'French', 'Français', 1, NOW()),
    ('ar', 'Arabic', 'العربية', 0, NOW()),
    ('pt', 'Portuguese', 'Português', 0, NOW()),
    ('sw', 'Swahili', 'Kiswahili', 0, NOW()),
    ('ha', 'Hausa', 'Hausa', 0, NOW()),
    ('es', 'Spanish', 'Español', 0, NOW()),
    ('zh', 'Chinese (Simplified)', '中文', 0, NOW());


-- ============================================================================
-- SECTION 2: PHARMACY MODULE — legacy schema (unmodified, see the header)
-- ============================================================================
-- Source: management/pharmacy/database/db.sql / root db.sql. The
-- CREATE DATABASE, USE, and DROP TABLE IF EXISTS statements from that
-- standalone file are intentionally omitted here — dbumi.sql is one shared
-- database, and these tables must not be dropped when other sections of
-- this file are (re-)applied.

CREATE TABLE `store` (
  `store_id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(100) UNIQUE NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `city` VARCHAR(100) DEFAULT 'Cameroon',
  `country` VARCHAR(100) DEFAULT 'Cameroon',
  `currency` VARCHAR(10) DEFAULT 'XAF',
  `store_status` VARCHAR(50) DEFAULT 'active',
  `registration_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME,
  UNIQUE KEY `unique_username` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_method` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `method_name` VARCHAR(100) NOT NULL,
  `method_code` VARCHAR(50) UNIQUE NOT NULL,
  `category` VARCHAR(50) DEFAULT 'mobile_money',
  `is_active` TINYINT DEFAULT 1,
  `description` TEXT,
  `date_added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_customer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `customertype` VARCHAR(50) DEFAULT 'Regular',
  `customerstatus` VARCHAR(50) DEFAULT 'active',
  `points` INT DEFAULT 0,
  `due` DECIMAL(10,2) DEFAULT 0,
  `wallet` DECIMAL(10,2) DEFAULT 0,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_supplier` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `receivable` DECIMAL(10,2) DEFAULT 0,
  `payable` DECIMAL(10,2) DEFAULT 0,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_medicine_category` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `img` VARCHAR(255),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_brand` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `details` TEXT,
  `img` VARCHAR(255),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `medicine_unit` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `unit` VARCHAR(50) NOT NULL UNIQUE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `medicine_type` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `type` VARCHAR(50) NOT NULL UNIQUE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_medicine` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `expiredate` DATE,
  `abroad` VARCHAR(50),
  `name` VARCHAR(200) NOT NULL,
  `details` TEXT,
  `category` INT,
  `brand` INT,
  `strength` VARCHAR(100),
  `unit` INT,
  `code` VARCHAR(100) UNIQUE,
  `shelf` VARCHAR(100),
  `cost` DECIMAL(10,2) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `qty` INT DEFAULT 0,
  `img` VARCHAR(255),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`category`) REFERENCES `p_medicine_category`(`id`),
  FOREIGN KEY (`brand`) REFERENCES `p_brand`(`id`),
  FOREIGN KEY (`unit`) REFERENCES `medicine_unit`(`id`),
  INDEX `idx_store` (`store`),
  INDEX `idx_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_supply` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `title` VARCHAR(200),
  `supplier` INT,
  `total` DECIMAL(10,2),
  `payable` DECIMAL(10,2),
  `paid` DECIMAL(10,2),
  `due` DECIMAL(10,2),
  `details` TEXT,
  `supplydate` DATE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`supplier`) REFERENCES `p_supplier`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_purchase_summary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100) UNIQUE,
  `store` INT NOT NULL,
  `total_qty` INT,
  `total_price` DECIMAL(12,2),
  `total_cost` DECIMAL(12,2),
  `payment_method` VARCHAR(100),
  `coupon` VARCHAR(100),
  `discounted` DECIMAL(10,2) DEFAULT 0,
  `payable` DECIMAL(12,2),
  `paid_status` VARCHAR(50) DEFAULT 'pending',
  `transection_id` VARCHAR(100),
  `transection_submit_date` DATETIME,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_purchase` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100),
  `store` INT NOT NULL,
  `product_id` INT,
  `product` VARCHAR(200),
  `qty` INT,
  `cost` DECIMAL(10,2),
  `totalcost` DECIMAL(12,2),
  `price` DECIMAL(10,2),
  `totalprice` DECIMAL(12,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_invoice_summary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100) UNIQUE,
  `store` INT NOT NULL,
  `client` VARCHAR(100),
  `total_qty` INT,
  `total_price` DECIMAL(12,2),
  `total_cost` DECIMAL(12,2),
  `payment_method` VARCHAR(100),
  `paid` DECIMAL(12,2),
  `due` DECIMAL(12,2),
  `discount_type` VARCHAR(10),
  `discount` DECIMAL(10,2) DEFAULT 0,
  `payable` DECIMAL(12,2),
  `order_date` DATETIME,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_invoice` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice` VARCHAR(100),
  `store` INT NOT NULL,
  `product_id` INT,
  `product` VARCHAR(200),
  `qty` INT,
  `cost` DECIMAL(10,2),
  `totalcost` DECIMAL(12,2),
  `price` DECIMAL(10,2),
  `totalprice` DECIMAL(12,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`),
  INDEX `idx_invoice` (`invoice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_return_summary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `invoice` VARCHAR(100),
  `customer` VARCHAR(100),
  `customer_id` INT,
  `grand_price` DECIMAL(12,2),
  `customer_paid` DECIMAL(12,2),
  `returnable` DECIMAL(12,2),
  `returned` DECIMAL(12,2),
  `discount` DECIMAL(10,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`customer_id`) REFERENCES `p_customer`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_return_product` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `return_id` INT,
  `product_id` INT,
  `product_name` VARCHAR(200),
  `qty` INT,
  `price` DECIMAL(10,2),
  `total` DECIMAL(12,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`return_id`) REFERENCES `p_return_summary`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_damage_product` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `product` INT,
  `total_qty` INT,
  `damage_qty` INT,
  `cost` DECIMAL(10,2),
  `price` DECIMAL(10,2),
  `note` TEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_payment` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `transaction` VARCHAR(100),
  `payment_date` DATE,
  `payment_type` VARCHAR(50),
  `account_type` VARCHAR(50),
  `name` VARCHAR(100),
  `phone` VARCHAR(20),
  `amount` DECIMAL(12,2),
  `payment_method` VARCHAR(100),
  `details` TEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`),
  INDEX `idx_payment_date` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_expense_category` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `p_expense` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `category` INT,
  `amount` DECIMAL(12,2),
  `details` TEXT,
  `expense_date` DATE,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`category`) REFERENCES `p_expense_category`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cart` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user` INT NOT NULL,
  `product_id` INT,
  `product_name` VARCHAR(200),
  `qty` INT DEFAULT 1,
  `price` DECIMAL(10,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`user`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_user` (`user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `return_cart` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `product_id` INT,
  `product_name` VARCHAR(200),
  `qty` INT DEFAULT 1,
  `price` DECIMAL(10,2),
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `p_medicine`(`id`),
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `store` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100),
  `phone` VARCHAR(20),
  `address` TEXT,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`store`) REFERENCES `store`(`store_id`) ON DELETE CASCADE,
  INDEX `idx_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_store_active ON `store`(`store_status`);
CREATE INDEX idx_registration ON `store`(`registration_date`);
CREATE INDEX idx_medicine_store ON `p_medicine`(`store`);
CREATE INDEX idx_medicine_category ON `p_medicine`(`category`);
CREATE INDEX idx_invoice_store ON `p_invoice_summary`(`store`, `order_date`);
CREATE INDEX idx_purchase_store ON `p_purchase_summary`(`store`, `date`);

-- ============================================================================
-- END dbumi.sql — CORE + PHARMACY MODULE (Phase 4 content)
-- ============================================================================
